"""sa_relationship

Revision ID: 6f445d658563
Revises: 737228a9f3ca
Create Date: 2022-06-10 21:51:05.505718

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6f445d658563'
down_revision = '737228a9f3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
